# Docs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ".github:"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/go/enrich"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go.mod:"

  - package-ecosystem: "gomod"
    directory: "/go/flatten"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go.mod:"

  - package-ecosystem: "gomod"
    directory: "/go/kafka-pg-demo"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go.mod:"

  - package-ecosystem: "gomod"
    directory: "/go/simple"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go.mod:"

  # Maintain dependencies for Node
  - package-ecosystem: "npm"
    directory: "/javascript/ecommerce-order-alerting"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "package.json:"

  - package-ecosystem: "npm"
    directory: "/javascript/postgres-snowflake-google-maps-enrich"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "package.json:"

  - package-ecosystem: "npm"
    directory: "/javascript/real-time-data-lake-ingestion"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "package.json:"

  - package-ecosystem: "npm"
    directory: "/javascript/search-indexing-algolia"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "package.json:"

  - package-ecosystem: "npm"
    directory: "/javascript/users-demo"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "package.json:"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/javascript/ecommerce-order-alerting/lib/function-deploy/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/javascript/ecommerce-order-alerting/packages/turbine-js-cli/templates"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "javascript/postgres-snowflake-google-maps-enrich/lib/function-deploy/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/javascript/postgres-snowflake-google-maps-enrich/packages/turbine-js-cli/templates"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "javascript/real-time-data-lake-ingestion/lib/function-deploy/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/javascript/real-time-data-lake-ingestion/packages/turbine-js-cli/templates"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "javascript/search-indexing-algolia/lib/function-deploy/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/javascript/search-indexing-algolia/packages/turbine-js-cli/templates"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/javascript/users-demo/lib/function-deploy/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/javascript/users-demo/packages/turbine-js-cli/templates"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/python/delta-table"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "requirements.txt:"

  - package-ecosystem: "pip"
    directory: "/python/ecommerce-order-alerting"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "requirements.txt:"

  - package-ecosystem: "pip"
    directory: "/python/enrich"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "requirements.txt:"

  - package-ecosystem: "pip"
    directory: "/python/notion-s3-python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "requirements.txt:"

  - package-ecosystem: "pip"
    directory: "/python/python-sample-data-app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "requirements.txt:"

  - package-ecosystem: "docker"
    directory: "/python/delta-table/src/turbine/function-deploy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/python/ecommerce-order-alerting/src/turbine/function-deploy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/python/enrich/src/turbine/function-deploy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/python/notion-s3-python/src/turbine/function-deploy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  - package-ecosystem: "docker"
    directory: "/python/python-sample-data-app/src/turbine/function-deploy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"

  # Maintain dependencies for Ruby
