source 'https://rubygems.org'

gem 'turbine', source: 'https://gem.fury.io/meroxa/'
# gem 'turbine', path: '../../../turbine-core-grpc/lib/ruby/turbine'
# gem 'turbine', github: "meroxa/turbine", branch: "ah/ruby"
