name: Enrich (go) CI
on:
  pull_request:
    paths:
    - go/enrich/**
jobs:
  build:
    name: Enrich (Go) Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.19
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Build Enrich
      working-directory: go/enrich
      run: go build -mod=vendor ./...
  golangci:
    name: Enrich (go) Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - uses: actions/checkout@v3
      - name: golangci-lint for enrich
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 4m0s
          working-directory: go/enrich
  vet:
    name: Enrich (go) Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vet for enrich
        working-directory: go/enrich
        run: go vet ./...
  test:
    name: Enrich (go) Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Run tests for enrich
        working-directory: go/enrich
        run: |
         go test -v ./...
