name: CI
on:
  pull_request:
#    paths:
#      - 'flatten/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Build Flatten
      working-directory: flatten
      run: go build -mod=vendor ./...
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: actions/checkout@v3
      - name: golangci-lint for flatten
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 4m0s
          working-directory: flatten
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vet for flatten
        working-directory: flatten
        run: go vet ./...
  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Run tests for flatten
        working-directory: flatten
        run: |
         go test -v ./...
  run:
    name: Run
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CLI
        run: brew tap meroxa/taps && brew install meroxa
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Run flatten with CLI
        working-directory: flatten
        run: |
          go mod vendor
          meroxa apps run
