name: Flatten CI
on:
  pull_request:
    paths:
      - 'go/flatten/**'
jobs:
  build:
    name: Flatten Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Build Flatten
      working-directory: go/flatten
      run: | # flatten is special
        go mod vendor
        go build -mod=vendor ./...
  golangci:
    name: Flatten Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: actions/checkout@v3
      - name: Flatten vendor
        working-directory: go/flatten
        run: |
          go mod vendor
      - name: golangci-lint for flatten
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 4m0s
          working-directory: go/flatten
  vet:
    name: Flatten Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vet for flatten
        working-directory: go/flatten
        run: |
          go mod vendor
          go vet ./...
  test:
    name: Flatten Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Run tests for flatten
        working-directory: go/flatten
        run: |
          go mod vendor
          go test -v ./...
  run:
    name: Flatten Run
    needs: [ build ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Install CLI
        run: brew tap meroxa/taps && brew install meroxa
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Run flatten with CLI
        working-directory: go/flatten
        run: |
          go mod vendor
          ls -lah
          meroxa apps run
