name: Javascript CI
on:
  pull_request:
#    paths:
#    - javascript/**
jobs:
  pretty:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: prettier:check for ecommerce-order-alerting
        working-directory: javascript/ecommerce-order-alerting
        run: |
          npm install
          yarn run prettier:check
      - name: prettier:check for postgres-snowflake-google-maps-enrich
        working-directory: javascript/postgres-snowflake-google-maps-enrich
        run: |
          npm install
          yarn run prettier:check
      - name: prettier:check for real-time-data-lake-ingestion
        working-directory: javascript/real-time-data-lake-ingestion
        run:  |
          npm install
          yarn run prettier:check
      - name: prettier:check for search-indexing-algolia
        working-directory: javascript/search-indexing-algolia
        run:  |
          npm install
          yarn run prettier:check
      - name: prettier:check for users-demo
        working-directory: javascript/users-demo/meroxa_user_demo_data_app
        run:  |
          npm install
          yarn run prettier:check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Run tests for ecommerce-order-alerting
        working-directory: javascript/ecommerce-order-alerting
        run:  |
          npm install
          npm run test
      - name: Run tests for real-time-data-lake-ingestion
        working-directory: javascript/real-time-data-lake-ingestion
        run:  |
          npm install
          npm run test
  run:
    name: Run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install CLI
        run: brew tap meroxa/taps && brew install meroxa
      - name: Run real-time-data-lake-ingestion with CLI
        working-directory: javascript/real-time-data-lake-ingestion
        run: |
          npm install
          meroxa apps run
      - name: Run users-demo with CLI
        working-directory: javascript/users-demo/meroxa_user_demo_data_app
        run: |
          npm install
          meroxa apps run
          
    
