name: Ruby CI
on:
  pull_request:
    paths:
    - ruby/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Ruby
        uses: actions/setup-ruby@v3
        with:
          ruby-version: '3.1.4'
          bundler-cache: true
      - name: Run tests for simple-app
        working-directory: ruby/simple
        run: |
          bundle install
          bundle exec ruby app_test.rb


